---
host: 0.0.0.0
port: 8888
backend_host: localhost
backend_port: 4242
pidfile: /tmp/protector.pid
logfile: /tmp/protector.log
safe_mode: False
verbose: 2
db:
  type: redis
  expire: 604800 # data ttl 1 week
  redis:
    host: localhost
    port: 6379
    password: ""
rules:
  query_no_tags_filters:
  query_no_aggregator:
  too_many_datapoints: 10000 # number
  exceed_time_limit:
    limit:    20    # query duration limit in seconds
    throttle: 300   # throttle time in seconds
    adaptive: 1.5   # preempts limit and throttle settings
  query_old_data:      90    # days
  exceed_frequency:    30    # seconds
# You can create a blockedlist for metric names
# Queries matching these patterns will be blocked
blockedlist:
  - bad\.metric
  - ^regex_metric$
  - ^application_release$
  - .*java.*boot.*version.*
# You can create an allowedlist for metric names
# Queries matching these patterns will skip the filters (if not rejected by the blockedlist!)
allowedlist:
  - test\.e2e\.
