---
host: localhost
port: 8888
backend_host: localhost
backend_port: 4343
pidfile: /tmp/protector.pid
logfile: /tmp/protector.log
verbose: 2
db:
  type: redis
  redis:
    host: localhost
    port: 6379
    password: ""
rules:
  query_no_tags_filters:
  query_no_aggregator:
  too_many_datapoints: 10000 # number
  exceed_time_limit:   20    # seconds
  query_old_data:      90    # days
  exceed_frequency:    30    # seconds
# You can blacklist series names
# Queries matching these patterns will be blocked
blacklist:
  - grafana\.
  - ^php_serverstart$
  - ^c_test_events$
  - ^application_release$
  - .*java.*boot.*version.*
