{
 "title": "OpenTSDB Protector DEV",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Memory stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"protector\"}"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"protector\"}"
      }
     ]
    }
   ]
  },
  { "title": "Protector stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rejected percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(sum(requests_blocked_total)/sum(requests_total)) * 100"
    }
   ]
  },
  {
   "title": "Rejected by rule",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(too_many_datapoints_count_total)"
    },
    {
     "expr": "SUM(exceed_time_limit_count_total)"
    },
    {
     "expr": "SUM(query_no_aggregator_count_total)"
    },
    {
     "expr": "SUM(query_no_tags_filters_count_total)"
    },
    {
     "expr": "SUM(exceed_frequency_count_total)"
    },
    {
     "expr": "SUM(query_old_data_count_total)"
    },
    {
     "expr": "SUM(requests_blacklisted_matched_total)"
    }
   ]
  },
  {
   "title": "Protector req total / blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(requests_total)" },
    { "expr": "sum(requests_blocked_total)" }
   ]
  },
  {
   "title": "OpenTSDB latencies histogram / 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tsdb_request_latency_seconds_bucket[10m])) by (le)"
    }
   ]
  },
  {
   "title": "Query activity / increase per 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(requests_total[10m])" }
   ]
  },
  {
   "title": "OpenTSDB latencies / increase per 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tsdb_request_latency_seconds_bucket[10m])) by (le)"
    }
   ]
  },
  {
   "title": "Datapoints served / increase per 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(datapoints_served_count_total[10m])"
    }
   ]
  }
 ]
}